Fix node modules

diff --git a/.github/workflows/deploy-from-dev-repository-volta.yaml b/.github/workflows/deploy-from-dev-repository-volta.yaml
--- a/.github/workflows/deploy-from-dev-repository-volta.yaml
+++ b/.github/workflows/deploy-from-dev-repository-volta.yaml
@@ -60,20 +60,18 @@ jobs:
           set -x
           cd ${{ env.LOCAL_DEV_REPOSITORY }}
           pwd && ls -la
-          jq -V
+          test ! -e package.json && echo "Error: package.json does not exist." && exit 1
           ${HOME}/.volta/bin/volta install node@$(jq -r .volta.node package.json)
           test ! -e package-lock.json && echo "Error: package-lock.json does not exist." && exit 1
           ${HOME}/.volta/bin/volta which node
           ${HOME}/.volta/bin/volta which npm
           ${HOME}/.volta/bin/volta run --bundled-npm npm ci
-          ${HOME}/.volta/bin/volta run node -v
-          ${HOME}/.volta/bin/volta run --bundled-npm npm -v
         shell: bash
       - name: Build react
         run: |
           cd ${{ env.LOCAL_DEV_REPOSITORY }}
           pwd && ls -la
-          npm run build
+          ${HOME}/.volta/bin/volta run --bundled-npm npm run build
       - name: Copy build artifacts
         run: |
           cp -pr ${{ env.LOCAL_DEV_REPOSITORY }}/dist/* ${{ env.LOCAL_PROD_REPOSITORY }}/
